version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
